name: Run test suite

on:
  pull_request:
    branches:
      - master
      - dev-progressive
  push:
    branches:
      - master
      - dev-progressive

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'npm'
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - run: npm install
      - run: CHROME_BIN=$(which chrome) npm run test
